---
development:
  cloud_name: dlb7dnwss
  api_key: '948836529848258'
  api_secret: Dpx5BA_ZufPFrYMuQmdevzcJiYg
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dlb7dnwss
  api_key: '948836529848258'
  api_secret: Dpx5BA_ZufPFrYMuQmdevzcJiYg
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dlb7dnwss
  api_key: '948836529848258'
  api_secret: Dpx5BA_ZufPFrYMuQmdevzcJiYg
  enhance_image_tag: true
  static_file_support: false
